plugins {
    //noinspection JavaPluginLanguageLevel
    id("java-library")
    id("org.jetbrains.kotlin.jvm")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
    withSourcesJar()
    withJavadocJar()
}

repositories {
    google()
    mavenCentral()
    maven { url = "https://jitpack.io" }
}

dependencies {

    // kotlin.Result extensions
    implementation("com.github.siboxd:kotlin-result-extension:1.3.2")

    // Testing dependencies
    testImplementation("junit:junit:4.13.2")
}